### ISSUE TITLE
How is this extension different to mattpocock/ts-error-translator?

### ISSUE THREAD

**Issue by ooker777** [jliocsar/better-ts-errors#3]
[mattpocock/ts-error-translator](https://github.com/mattpocock/ts-error-translator "mattpocock/ts-error-translator: VSCode extension to turn TypeScript errors into plain English")

**Comment by jliocsar** [comment]
As stated on the README of this repo, this project was highly inspired by Matt's, *but it's not the same*.
While this extension merely matches TS error messages against their codes to provide basic syntax highlight and such, Matt's _actually_ translates them to a more user-friendly way, explaining the error and adding details.
Different extensions for different purposes.

**Comment by ooker777** [comment]
I know that it's different. I just want to see the difference clearer.

For what purpose that "matches TS error messages against their codes to provide basic syntax highlight and such" be more suitable than "translates them to a more user-friendly way, explaining the error and adding details"? I still don't see it

**Comment by jliocsar** [comment]
Explaining the errors in a different way is different than applying syntax highlight to already existing errors that are output by the TS compiler.

For reference you can check [this](https://github.com/microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json), which is what the extension currently fetches under the hood.
It's simply applying syntax highlight and parsing the already existing diagnostic messages from the TS compiler -- which is different than explaining them in a different, more understandable manner.

Either way, this extension isn't really working as it's supposed to at the moment, as it's not listing all errors as you'd expect (thanks to the VSCode diagnostics not having all error codes in them).

Now, to explain in a simple, easy to understand way:
- If you _do not want the TS Compiler error messages_, but rather a digested version of it (i.e. more detailed), use [mattpocock/ts-error-translator](https://github.com/mattpocock/ts-error-translator).
- If you _want the TS Compiler error messages_, but with syntax highlight, properly parsed TS snippets etc, then you can use `better-ts-errors` instead.

The thing is, to my use case, I didn't want a full-fledged detailed explanation of all my compiler errors, I just wanted syntax highlight to the TS snippets in error messages itself.
I don't need to learn the errors, just need a better way to read them.

Do this, install both extensions and compare the output in a `.ts` file with this snippet:

```ts
const a: " 'oh no'" = 10
```

The `ts-error-translator` will output something like `"Translation: I was expecting a type matching A, but instead you passed B."`, with the original message in a simple string format:

```
Type '10' is not assignable to type '" 'oh no'"'.
```

The `better-ts-errors` extension will instead format this single error message to a more readable format:

**`🛑 Error`** [(ts 2322)](https://typescript.tv/errors/#TS2322)
 
Type

```ts
10
```

is not assignable to type

```ts
" 'oh no'"
```

Of course in this simple scenario the parsed output isn't _that_ helpful, but when you have deep, complex objects and huge error messages -- then this extension does help a lot.
As you can see, from both outputs, they're for different purposes.
You can even use both at the same time, in case you want:
- Error messages translated to a simpler way to understand (when compared to the original diagnostic messages one);
- Error messages parsed with syntax highlight, so it's easier to tell which type is which etc.
