### ISSUE TITLE
Version 1.7.7 of the software causes the editor to freeze.

### ISSUE THREAD

**Issue by ShinChven** [jliocsar/better-ts-errors#5]
Version 1.7.7 of the software causes the editor to freeze.

**Comment by tekikaito** [comment]
In my case, VSCode was slowed down a lot.

**Comment by tmgasek** [comment]
same here, caused every editor operation to freeze up due to 100% CPU usage

**Comment by WilliamIPark** [comment]
hello other developers having a bad day

**Comment by jliocsar** [comment]
Hey folks, so sorry about this.

I'm pushing a fix for this, but it's merely a version revert as I'm not sure what's causing this yet.
Btw, are you using any other extensions that add that sort of information of hover, such as ESLint or something alike? I'm afraid the latest changes I did are being affected by that or something.

Anyhow, sorry for the inconvenience, I know how frustrating it is to have your CPU being hammered by something like this lol
To be fair, I really didn't know this many people were using the extension, so thanks for that.

(edit: please let me know if the "new" version is still causing high CPU loads, cause if it is then I'm clearly incompetent kek)

**Comment by jliocsar** [comment]
Well fellas, I guess I've fixed it on v1.8.2?

Apparently it's not hanging anymore, I've also added the latest code with some changes (related information stuff, if you use the extension on daily basis this might help a lot).
_Mental note: other extensions might generate new diagnostics for TS files, so these need to be filtered out of the whole thing._

Anyhow, please let me know if you face any other issues with it.
Sorry again about it, cheers!

**Comment by WilliamIPark** [comment]
Thanks for the fix, the extension is awesome! For what it's worth it gave our team who suffered other dev environment issues this week a laugh and a sigh of relief when we realised it wasn't related.
